# Default values for home-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sensor_service:
  image:
    repository: mcostea/homemanager_sensor-service
    tag: stable
    pullPolicy: Always

sensor_listener:
  image:
    repository: mcostea/homemanager_sensor-listener
    tag: stable
    pullPolicy: Always
  sensor_service_url: "http://home_manager_sensor-service"

nginx:
  image:
    repository: mcostea/homemanager_nginx
    tag: stable
    pullPolicy: Always

postgres:
  image:
    repository: mcostea/timescaledb
    tag: latest-pg10
    pullPolicy: Always

rabbitmq:
  image:
    repository: mcostea/homemanager_rabbitmq
    tag: stable
    pullPolicy: Always
  host: "home_manager_rabbitmq"
  username: "rabbit"

persistence:
  accessMode: ReadWriteOnce
  size: 25Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
