# Default values for home-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sensor_service:
  image:
    repository: mcostea/homemanager_sensor-service
    tag: stable
    pullPolicy: Always

sensor_listener:
  image:
    repository: mcostea/homemanager_sensor-listener
    tag: stable
    pullPolicy: Always
  sensor_service_url: "http://home-manager-sensor-service.default.svc.cluster.local"

postgres:
  image:
    repository: mcostea/timescaledb
    tag: latest-pg10
    pullPolicy: Always

rabbitmq:
  image:
    repository: mcostea/homemanager_rabbitmq
    tag: stable
    pullPolicy: Always
  host: "home-manager-rabbit-service.default.svc.cluster.local"
  username: "rabbit"

weather:
  image:
    repository: mcostea/homemanager_weather-sensor
    tag: stable
    pullPolicy: Always

persistence:
  accessMode: ReadWriteOnce
  size: 25Gi
  storageClass: -

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
