trigger:
- master

jobs:
- job: "multi-platform-build"
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: templates/build-steps.yml
    parameters:
      runTests: "true"

- job: "sensors"
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - bash: |
      pip install -U platformio
      platformio upgrade --dev
      platformio update
  - bash: |
      platformio test -e native
    workingDirectory: "$(Build.SourcesDirectory)/Sensors/ESPTempSensor"
  - bash: |
      platformio run -e nodemcuv2
    workingDirectory: "$(Build.SourcesDirectory)/Sensors/ESPTempSensor"
