trigger:
- master

pool:
  name: Default

steps:
- task: Docker@1
  displayName: 'Build nginx'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: deploy/nginx/Dockerfile
    imageName: 'mcostea/homemanager_nginx:$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@1
  displayName: 'Build RabbitMQ'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: deploy/rabbitmq/Dockerfile
    imageName: 'mcostea/homemanager_rabbitmq:$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@1
  displayName: 'Build sensor service'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: SensorService/Dockerfile
    imageName: 'mcostea/homemanager_sensor-service:$(Build.BuildId)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '$(System.DefaultWorkingDirectory)'

- task: Docker@1
  displayName: 'Build sensor service tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: SensorService/Dockerfile
    arguments: '--pull --target testrunner'
    imageName: 'mcostea/homemanager_sensor-service:test'
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@1
  displayName: 'Run sensor service tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Run an image'
    imageName: 'mcostea/homemanager_sensor-service:test'
    envVars: 'CODECOV_TOKEN=22560ceb-5679-418d-be9c-8d61262de8ff'

- task: Docker@1
  displayName: 'Build sensor listener'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: SensorListener/Dockerfile
    imageName: 'mcostea/homemanager_sensor-listener:$(Build.BuildId)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '$(System.DefaultWorkingDirectory)'

- task: Docker@1
  displayName: 'Build weather sensor'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerFile: Sensors/WeatherSensor/Dockerfile
    imageName: 'mcostea/homemanager_weather-sensor:$(Build.BuildId)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '$(System.DefaultWorkingDirectory)'

- bash: |
   # Write your commands here   
   # Use the environment variables input below to pass secret variables to this script
   echo "mcostea/homemanager_nginx" > images.txt
   echo "mcostea/homemanager_rabbitmq" >> images.txt
   echo "mcostea/homemanager_sensor-service" >> images.txt
   echo "mcostea/homemanager_sensor-listener" >> images.txt
   echo "mcostea/homemanager_weather-sensor" >> images.txt
  displayName: 'Bash Script'

- task: Docker@1
  displayName: 'Push images'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    pushMultipleImages: true
    imageNamesPath: images.txt
