trigger:
- master

jobs:
- job: "arm"
  pool:
    name: Default
  steps:
  - template: templates/build-steps.yml
    parameters:
      arch: "arm"
      runTests: "false"

- job: "amd64"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/build-steps.yml
    parameters:
      arch: "amd64"
      runTests: "true"

- job: "manifest"
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn:
  - arm
  - amd64
  steps:
  - bash: |
      # Write your commands here
      # Use the environment variables input below to pass secret variables to this script
      mkdir -p ~/.docker
      echo '{ "experimental": "enabled", "auths": { "https://index.docker.io/v1/": { "auth": "$(docker_hub_auth)", "email": "" } } }' > ~/.docker/config.json
      echo "mcostea/homemanager_rabbitmq:$(Build.BuildId)-amd64" >> images.txt
      echo "mcostea/homemanager_sensor-service:$(Build.BuildId)-amd64" >> images.txt
      echo "mcostea/homemanager_sensor-listener:$(Build.BuildId)-amd64" >> images.txt
      echo "mcostea/homemanager_weather-sensor:$(Build.BuildId)-amd64" >> images.txt

      docker --config ~/.docker manifest create mcostea/homemanager_rabbitmq:$(Build.BuildId) mcostea/homemanager_rabbitmq:$(Build.BuildId)-arm mcostea/homemanager_rabbitmq:$(Build.BuildId)-amd64
      docker --config ~/.docker manifest create mcostea/homemanager_sensor-service:$(Build.BuildId) mcostea/homemanager_sensor-service:$(Build.BuildId)-arm mcostea/homemanager_sensor-service:$(Build.BuildId)-amd64
      docker --config ~/.docker manifest create mcostea/homemanager_sensor-listener:$(Build.BuildId) mcostea/homemanager_sensor-listener:$(Build.BuildId)-arm mcostea/homemanager_sensor-listener:$(Build.BuildId)-amd64
      docker --config ~/.docker manifest create mcostea/homemanager_weather-sensor:$(Build.BuildId) mcostea/homemanager_weather-sensor:$(Build.BuildId)-arm mcostea/homemanager_weather-sensor:$(Build.BuildId)-amd64

      docker --config ~/.docker manifest push mcostea/homemanager_rabbitmq:$(Build.BuildId)
      docker --config ~/.docker manifest push mcostea/homemanager_sensor-service:$(Build.BuildId)
      docker --config ~/.docker manifest push mcostea/homemanager_sensor-listener:$(Build.BuildId)
      docker --config ~/.docker manifest push mcostea/homemanager_weather-sensor:$(Build.BuildId)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))