version: "3"
services:
        nginx:
                image: mcostea/homemanager_nginx
                ports:
                        - "80:80"
                        - "443:443"
        sensor-service:
                image: mcostea/homemanager_sensor-service
        postgres:
                image: arm32v7/postgres
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_PASSWORD: password
                volumes:
                        - /media/datadisk0/timescale:/var/lib/postgresql/data
                deploy:
                        placement:
                                 constraints:
                                         - node.role == manager
