apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-manager.fullname" . }}-postgres-service
  labels:
{{ include "home-manager.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres

  selector:
    app: rabbitmq
