apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "home-manager.fullname" . }}-postgres
  labels:
{{ include "home-manager.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      strategy:
        type: Recreate
      initContainers:
      - name: init-chmod-data
        image: debian:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - |
            mkdir -p /var/lib/postgresql/data
            chmod 700 /var/lib/postgresql/data
            chown -R 70:70 /var/lib/postgresql/data
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        securityContext:
          runAsUser: 70
          runAsGroup: 70
          fsGroup: 70
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "home-manager.fullname" . }}
              key: postgres-password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "home-manager.fullname" . }}-postgres-pvc
