apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "home-manager.fullname" . }}-rabbit
  labels:
{{ include "home-manager.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        ports:
        - containerPort: 15672
        - containerPort: 1883
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 8883
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "{{ .Values.rabbitmq.username }}"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "home-manager.fullname" . }}
              key: rabbitmq-password
