apiVersion: v1
kind: Secret
metadata:
    name: {{ template "home-manager.fullname" . }}
type: Opaque
data:
    {{ if .Values.rabbitmq.password }}
    rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
    {{ else }}
    rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
    {{ end }}
    {{ if .Values.postgres.password }}
    postgres-password: {{ .Values.postgres.password | b64enc | quote }}
    {{ else }}
    postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
    {{ end }}
