apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "home-manager.fullname" . }}-sensor-service-ingress
spec:
  rules:
  - host: sensor-service.mcostea.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "home-manager.fullname" . }}-sensor-service
          servicePort: web
