apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-manager.fullname" . }}-sensor-service
  labels:
{{ include "home-manager.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    name: {{ include "home-manager.name" . }}-sensor
    app.kubernetes.io/instance: {{ .Release.Name }}
