version: "3.1"
services:
        nginx:
                image: mcostea/homemanager_nginx
                ports:
                        - "80:80"
                        - "443:443"
                logging:
                  driver: gcplogs
                  options:
                    gcp-project: home-manager-4516778
        sensor-service:
                image: mcostea/homemanager_sensor-service
                logging:
                  driver: gcplogs
                  options:
                    gcp-project: home-manager-4516778
        sensor-listener:
                image: mcostea/homemanager_sensor-listener
                environment:
                        RABBITMQ_HOST: "home_manager_rabbitmq"
                        RABBITMQ_USERNAME: "rabbit"
                        RABBITMQ_PASSWORD: "rabbit"
                        SENSOR_SERVICE_URL: "http://home_manager_sensor-service"
                logging:
                  driver: gcplogs
                  options:
                    gcp-project: home-manager-4516778
        postgres:
                image: mcostea/timescaledb:latest-pg10
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_PASSWORD: password
                volumes:
                        - /media/datadisk0/timescale:/var/lib/postgresql/data
                deploy:
                        placement:
                                 constraints:
                                         - node.role == manager
                logging:
                  driver: gcplogs
                  options:
                    gcp-project: home-manager-4516778
        rabbitmq:
                image: mcostea/homemanager_rabbitmq
                ports:
                        - "15672:15672"
                        - "1883:1883"
                        - "5671:5671"
                        - "5672:5672"
                        - "8883:8883"
                logging:
                  driver: gcplogs
                  options:
                    gcp-project: home-manager-4516778

        weather-sensor:
          image: mcostea/homemanager_weather-sensor
          environment:
            WEATHER_LOCATION: "Cluj-Napoca"
            RABBITMQ_HOST: "home_manager_rabbitmq"
            HOME_ID: 1
          secrets:
            - OPENWEATHERMAP_APPID
          deploy:
            restart_policy:
              condition: any
              delay: 1h

secrets:
    OPENWEATHERMAP_APPID:
        external: true
