FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

# Dependencies
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY SensorListener/SensorListener.csproj SensorListener/
COPY Common/Common.csproj Common/
COPY Domain/Domain.csproj Domain/
RUN dotnet restore SensorListener/SensorListener.csproj
COPY . .
WORKDIR /src/SensorListener

# Build and publish
FROM build AS publish
RUN dotnet publish "SensorListener.csproj" -r linux-arm --self-contained -c Release -o /app
